{
  "formatVersion": "1.1",
  "component": {
    "group": "com.marslib",
    "module": "MARSLib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MARSLib-1.0.0.jar",
          "url": "MARSLib-1.0.0.jar",
          "size": 8803562,
          "sha512": "5e40aef184b9f0c25cd02e60fae13cec1d4834a18b67219a583b99676aa83abd4f69aff66ae7ecac00a4d36ed8f6abcc508350bf501a1d884f238fcdc10f0780",
          "sha256": "00bbffe279607226d72a9ba25c2e7cebeab5b8dca0d16cd7bca5a8649082ba6c",
          "sha1": "db728b999ea139ff3482c36df4c8a853a7ed28f4",
          "md5": "04f53fa84f7118fbfbc7a02641e014fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "org.ironmaple",
          "module": "maplesim-java",
          "version": {
            "requires": "0.4.0-beta-obstacles-fix"
          }
        },
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "MARSLib-1.0.0.jar",
          "url": "MARSLib-1.0.0.jar",
          "size": 8803562,
          "sha512": "5e40aef184b9f0c25cd02e60fae13cec1d4834a18b67219a583b99676aa83abd4f69aff66ae7ecac00a4d36ed8f6abcc508350bf501a1d884f238fcdc10f0780",
          "sha256": "00bbffe279607226d72a9ba25c2e7cebeab5b8dca0d16cd7bca5a8649082ba6c",
          "sha1": "db728b999ea139ff3482c36df4c8a853a7ed28f4",
          "md5": "04f53fa84f7118fbfbc7a02641e014fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MARSLib-1.0.0-sources.jar",
          "url": "MARSLib-1.0.0-sources.jar",
          "size": 145711,
          "sha512": "f12f373547b397e6cb2576189b60227ac694db1eea356fea0f3b8c55b3a2e1805e284b7f3011a8a0edfbab628c7fd872d1b75053869840706192ac232d82f0a9",
          "sha256": "c1b09c7a6e30bbf6693e1308c190df7a96c0ab3760db1c3296e97f66a01729a8",
          "sha1": "575105d70ebe3cdb9d9b6cc38f10a83febade61d",
          "md5": "0fc144d94a8f32cd33af532603fd6704"
        }
      ]
    }
  ]
}
