backend:
  name: github
  repo: MARSProgramming/MARSLib
  branch: master
  base_url: https://sveltia-cms-auth.david-huss.workers.dev

# Specify media paths
media_folder: "website/static/img"
public_folder: "/img"

# Optional: Add logo to the login screen
# logo_url: "https://your-logo-url-here.png"

collections:
  - name: "setup_tutorials"
    label: "🚀 Setup & Install"
    folder: "website/docs/tutorials/setup"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sidebar Position", name: "sidebar_position", widget: "number", required: false }
      - { label: "ID", name: "id", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "text" }

  - name: "framework_tutorials"
    label: "🧠 Framework Features"
    folder: "website/docs/tutorials/framework"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sidebar Position", name: "sidebar_position", widget: "number", required: false }
      - { label: "ID", name: "id", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "text" }

  - name: "elite_tutorials"
    label: "🏆 Elite Systems"
    folder: "website/docs/tutorials/elite"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sidebar Position", name: "sidebar_position", widget: "number", required: false }
      - { label: "ID", name: "id", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "text" }

  - name: "zero_to_hero"
    label: "🐣 Zero to Hero"
    folder: "website/docs/tutorials/zero-to-hero"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sidebar Position", name: "sidebar_position", widget: "number", required: false }
      - { label: "ID", name: "id", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "text" }
