{
  "formatVersion": "1.1",
  "component": {
    "group": "com.marslib",
    "module": "MARSLib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MARSLib-1.0.0.jar",
          "url": "MARSLib-1.0.0.jar",
          "size": 8802372,
          "sha512": "e9b30af2354f6a4f8babf913402f19f24c497e2e05ab547fd2c0075e1e2d48b85cbca8d9b313739fd09bbc6ed7ee663fb527d7dfc0aab437e109ee5bad676fa1",
          "sha256": "f85d308100ab1edf060e8d8daeb6557d30a45b9edc897ad3b3bbf849e099e2d6",
          "sha1": "ca1d61bf7b44d00fdcd74e3b06a7cc7eefe6a390",
          "md5": "0b10d2947b61531bafe79938811188a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "org.ironmaple",
          "module": "maplesim-java",
          "version": {
            "requires": "0.4.0-beta-obstacles-fix"
          }
        },
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "MARSLib-1.0.0.jar",
          "url": "MARSLib-1.0.0.jar",
          "size": 8802372,
          "sha512": "e9b30af2354f6a4f8babf913402f19f24c497e2e05ab547fd2c0075e1e2d48b85cbca8d9b313739fd09bbc6ed7ee663fb527d7dfc0aab437e109ee5bad676fa1",
          "sha256": "f85d308100ab1edf060e8d8daeb6557d30a45b9edc897ad3b3bbf849e099e2d6",
          "sha1": "ca1d61bf7b44d00fdcd74e3b06a7cc7eefe6a390",
          "md5": "0b10d2947b61531bafe79938811188a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MARSLib-1.0.0-sources.jar",
          "url": "MARSLib-1.0.0-sources.jar",
          "size": 144546,
          "sha512": "27befbec42add03943f97abd717914eaa94c60d1e41eca53411ef8c5df627f369631a2d413f8f5703777273efd3c036546e27bedd6253e94b1eb074521788db7",
          "sha256": "033df08244ab7e2b33640d6f3e204e98dcfde60c47a30f12586886f279c71a91",
          "sha1": "f9e235cba213d9e92d7d58ac9c232e3f146da916",
          "md5": "2d45e5f5975f38f4eadf1cdd1efb0784"
        }
      ]
    }
  ]
}
