name: Accessibility Check

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Cloudflare Deployment
        run: sleep 60

      - name: Run WCAG AA Audit
        run: |
          echo '{"chromeLaunchConfig": {"args": ["--no-sandbox", "--disable-setuid-sandbox"]}}' > pa11y.json
          npx pa11y https://marslib.pages.dev --standard WCAG2AA --config pa11y.json
